### ISSUE TITLE
Timeout is occureed when receive a first http request.

### ISSUE THREAD

**Issue by runceel** [kenakamu/clova-cek-sdk-csharp#4]
Hi @kenakamu ,

I'm using this library. I think this is pretty good!
However, I have an issue when receive a first http request.
When receive a first http request, this library get a pem file from `https://clova-cek-requests.line.me/.well-known/signature-public-key.pem` for request validation.
https://github.com/kenakamu/clova-cek-sdk-csharp/blob/master/clova-cek-sdk-csharp/ClovaClient.cs#L48

That is cause of request timeout. (I want to call another web api. However, because timeout will be occureed, then I can't call another web api.)
In official node.js library, there is embedded cert data.
https://github.com/line/clova-cek-sdk-nodejs/blob/master/src/verifier.ts#L19

If no license issue, then I think that embedded approach is better than current implementation.
How do you think?

**Comment by kenakamu** [comment]
The truth is, i hard coded before and replace it to calling it by thinking it maybe updated in the future. But for now i can revert back to original way.

**Comment by runceel** [comment]
I was thinking that same issues which maybe updated in the future.

However, in the official library, because there is embedded cert info, I guess that updating possibility is low.

**Comment by runceel** [comment]
Thank you for updating!
